### ISSUE TITLE
Add noise metric to output

### ISSUE THREAD

**Issue by GGAlanSmithee** [inigoflores/helium-miner-log-analyzer#1]
@inigoflores 

When running the tool with `./processlogs.php -l` both `RSSI` and `SNR` are outputted, but not `noise`. This is a simple calculation (`RSSI - SNR`) [source](https://support.cotxnetworks.com/support/solutions/articles/73000513839-how-to-solve-the-ambient-noise-problem-) but a bit cumbersome to effectively do yourself in the console.

I want to see this to better understand if I would benefit from a SAW filter or not.

_PS. If you don't have time to do it, but want it added, let me know and I'll do it. Was quite some time since I dabbled in php_ though!

Thanks!

**Comment by inigoflores** [comment]
Done!

Thanks for the feedback.

**Comment by GGAlanSmithee** [comment]
Thanks @inigoflores !
