### ISSUE TITLE
Looking For Sensecap M1 Support

### ISSUE THREAD

**Issue by Shadowofnight98** [inigoflores/helium-miner-log-analyzer#10]
looking to see if it is possible to support SensecapM1

**Comment by LDarnton** [comment]
I'm not sure how to implement this either, would be useful for sure.

**Comment by pokeplayer2** [comment]
It's not an issue: 
./processlogs.php -s 2022-04-01 -e 2022-04-02

Using logs in folder /var/log/miner/


General Witnesses Overview
----------------------------------
Total witnesses                   =    29  (3.19/hour)
Succesfully delivered             =    13 (44.83%)
Failed                            =    16 (55.17%)
  ├── Max retry    =   16 (55.17%)
  └── Crash/reboot =    0     (0%)

Max Retry Failure Reasons
----------------------------------
Timeout                           =     7 (24.14%)
Not Found                         =     8 (27.59%)
Other challenger issues           =     1  (3.45%)

Challengers
----------------------------------
Not Relayed                       =    19 (65.52%)
Relayed                           =     7 (24.14%)
Unknown (Probably Not Relayed)    =     3 (10.34%)
/opt/miner #
it just works as designed ;-)

**Comment by FuatPasa** [comment]
> It's not an issue: ./processlogs.php -s 2022-04-01 -e 2022-04-02
> 
> Using logs in folder /var/log/miner/
> 
> ## General Witnesses Overview
> Total witnesses = 29 (3.19/hour) Succesfully delivered = 13 (44.83%) Failed = 16 (55.17%) ├── Max retry = 16 (55.17%) └── Crash/reboot = 0 (0%)
> 
> ## Max Retry Failure Reasons
> Timeout = 7 (24.14%) Not Found = 8 (27.59%) Other challenger issues = 1 (3.45%)
> 
> ## Challengers
> Not Relayed = 19 (65.52%) Relayed = 7 (24.14%) Unknown (Probably Not Relayed) = 3 (10.34%) /opt/miner # it just works as designed ;-)

hi @pokeplayer2 , **./processlogs.php** command is not working with my sensecap. it says:

root@8547038:~# ./processlogs.php -s 2022-04-06 -e 2022-04-07
-sh: ./processlogs.php: No such file or directory

@inigoflores hi. would you please support this script into sensecap's too? I tried lot but no way :( please help

**Comment by inigoflores** [comment]
Hi

The problem with SenseCap is that the log folder is different between miners. I currently don't have a SenseCap, so I can't test it. 

Also, this tool will stop working in two weeks' time with the activation of HIP55, so it doesn't make much sense to invest more time in developing it.

But you should be able to run it from within the docker container. As per the Readme instructions:
```
If you are unable to install PHP at the miner OS, you should be able to do so inside docker. You can access the container with:

sudo docker exec -it miner sh   

You may need to replace "miner" with the name of the docker container running the Helium miner.

Once inside the docker container, run the following to install PHP.

apk add php-cli 

Note that any changes to the running docker container are not persistent and will be lost at the next reboot.
```

I hope it helps.

**Comment by steakneedy** [comment]
@inigoflores Hey there, great job with this script!

Was trying it lately with Sensecaps logs that I manually pulled to my local machine via SSH. 
Always getting this as an output:
```
Using logs in folder ./


Warning: Division by zero in C:\Users\...\processlogs.php on line 168

General Witnesses Overview
----------------------------------
Total witnesses                   =     1   (INF/hour)
Succesfully delivered             =     0     (0%)
Failed                            =     1   (100%)
  ├── Max retry    =    0     (0%)
  └── Crash/reboot =    1   (100%)

Max Retry Failure Reasons
----------------------------------
Timeout                           =     0     (0%)
Not Found                         =     0     (0%)
Other challenger issues           =     0     (0%)

Challengers
----------------------------------
Not Relayed                       =     0     (0%)
Relayed                           =     0     (0%)
Unknown (Probably Not Relayed)    =     1   (100%)
```

**Comment by inigoflores** [comment]
Hi

This is being discussed on #11. Apparently it has to do with running the tool on Windows. When did you download the tool?

**Comment by steakneedy** [comment]
> Hi
> 
> This is being discussed on #11. Apparently it has to do with running the tool on Windows. When did you download the tool?

Yes, lets continue there, thanks.

**Comment by inigoflores** [comment]
It should be now fixed. 

Please provide your path to the logs, see if I can add the logic for the tool to work on the SenseCap M1.

**Comment by steakneedy** [comment]
> It should be now fixed.
> 
> Please provide your path to the logs, see if I can add the logic for the tool to work on the SenseCap M1.

You could get the path and correct folder name through the "metadate.db" file in /mnt/data/docker/volumes which has the name of the folder written in one line:

`"Options":{}}xxxxxxx_miner-log{"Name":"xxxxxxx_miner-log","Driver":"local","Labels":{"io.balena.supervised":"true"}`

The final path of console.log will be /mnt/data/docker/volumes/xxxxxxx_miner-log/_data

**Comment by inigoflores** [comment]
That folder is already included in the code.

```
$logsFolders = [
        'Docker'         => '/var/log/miner/', //Also Controllino
        'Pisces P100'    => '/home/pi/hnt/miner/log/',
        'Sensecap M1'    => 'in /mnt/data/docker/volumes/xxxxxxx_miner-log/_data/',
        'Milesight UG65' => '/mnt/mmcblk0p1/miner_data/log/', //adding it for future use,as PHP and opkg are missing (OpenWrt)
        'Panther X2'     => '/opt/panther-x2/miner_data/log/',
        'RHF2S308'       => '/opt/helium/miner_data/log/'
];
```

What happens when you run the tool inside SenseCap? What is the output?

**Comment by steakneedy** [comment]
@inigoflores sorry my bad, it works when running inside Sensecap 😄

**Comment by inigoflores** [comment]
Cool" 😄  I've updated the Readme, for some reason it was missing from the list of supported devices.

**Comment by cristi134** [comment]
Can someone help a noob? I can't get this to work on my sensecap, i always get  "sudo: command not found" when trying "sudo docker exec -it miner sh   ". I'm not sure what should i replace "miner" with

**Comment by inigoflores** [comment]
I am currently testing the script on a Sensecap M1.

Instead of docker, you need to use balena. 

Use the following command to get the container name:

    root@ac7bbbc:~# balena ps 

    CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                 PORTS               NAMES
    3d4dc64326c5        a6457f6c5f0c                         "python3 /opt/status…"   2 hours ago         Up 2 hours                                 statusd_4829004_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    f6ac2cf27cd3        743a7241b071                         "sh /opt/start.sh"       2 hours ago         Up 2 hours                                 gateway-config_4829002_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    bd451c4209c7        7a8a79700674                         "/opt/miner/start-mi…"   2 hours ago         Up 2 hours                                 miner_4829001_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    d97c6e3ea12a        528fbbb123c6                         "python3 app.py"         2 hours ago         Up 2 hours                                 turbo-sync_4829005_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    210495f59dc6        7f72b548d14f                         "/opt/start.sh"          2 hours ago         Up 2 hours                                 dbus-server_4828999_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    62a09499121d        ac3c0f6e9f7a                         "./start.sh"             2 hours ago         Up 2 hours                                 pktfwd_4829000_2147054_fcde69c51c4bf3302d1c9eaba732f3c2
    d15abc6afd04        balena/aarch64-supervisor:v12.10.3   "/usr/src/app/entry.…"   19 months ago       Up 2 hours (healthy)                       balena_supervisor

Then you run the command replacing your container name: 

    root@ac7bbbc:~# balena exec -it miner_4829001_2147054_fcde69c51c4bf3302d1c9eaba732f3c2 sh

@steakneedy Did you manage to get it running in the host OS or inside the cotainer?

**Comment by cristi134** [comment]
Wonderful, thanks a lot, i got it working!

**Comment by steakneedy** [comment]
@inigoflores I'm running it inside the miner container.

**Comment by inigoflores** [comment]
> @inigoflores I'm running it inside the miner container.

I see. I previously understood that it worked at the host OS. So I guess the SenseCAP M1 is not supported "out of the box". 

Thanks!

**Comment by steakneedy** [comment]
> > @inigoflores I'm running it inside the miner container.
> 
> I see. I previously understood that it worked at the host OS. So I guess the SenseCAP M1 is not supported "out of the box".
> 
> Thanks!

Its fine I guess. 

Basically the "installation" is to
1. Get the name of miner container
`balena ps`
2. Replace "miner_xxxxxxx_xxxxxxx" with the according miner container name
`balena exec -it miner_xxxxxxx_xxxxxxx sh`
3. Then install php and download the script
`apk add php-cli 
wget -O processlogs.php https://raw.githubusercontent.com/inigoflores/helium-miner-log-analyzer/main/processlogs.php; chmod a+x processlogs.php`
4. Afterwards you can run the script


By the way, any clue how the new logs after LHS activiation will look like?
