### ISSUE TITLE
On Windows: Division by zero error

### ISSUE THREAD

**Issue by Secarius** [inigoflores/helium-miner-log-analyzer#11]
Dear Inigoflores, 
on windows i started gettin a division by zeror erro. Do you have any idea why? It was working some weeks ago.

```
Using logs in folder processlogs\logs
Warning: Division by zero in processlogs\processlogs.php on line 168

General Witnesses Overview  
----------------------------------
Total witnesses                   =     1   (INF/hour)
Succesfully delivered             =     0     (0%)
Failed                            =     1   (100%) 
  ├── Max retry    =    0     (0%) 
  └── Crash/reboot =    1   (100%) 

Max Retry Failure Reasons 
----------------------------------
Timeout                           =     0     (0%) 
Not Found                         =     0     (0%) 
Other challenger issues           =     0     (0%) 

Challengers 
----------------------------------
Not Relayed                       =     0     (0%) 
Relayed                           =     0     (0%) 
Unknown (Probably Not Relayed)    =     1   (100%) 
```

[console.log](https://github.com/inigoflores/helium-miner-log-analyzer/files/8453597/console.log)

**Comment by DCYeahThatsMe** [comment]
I am all of a sudden getting the same error as well:


Fatal error: Uncaught DivisionByZeroError: Division by zero in C:\MinerTools\processlogs\processlogs.php:168
Stack trace:
#0 C:\MinerTools\processlogs\processlogs.php(78): generateStats(Array)
#1 {main}
  thrown in C:\MinerTools\processlogs\processlogs.php on line 168

**Comment by inigoflores** [comment]
@Secarius, that's weird. It works for me with your logs

```
General Witnesses Overview
----------------------------------
Total witnesses                   =    29  (2.06/hour)
Succesfully delivered             =    18 (62.07%)
Failed                            =    11 (37.93%)
  ├── Max retry    =   11 (37.93%)
  └── Crash/reboot =    0     (0%)

Max Retry Failure Reasons
----------------------------------
Timeout                           =     7 (24.14%)
Not Found                         =     2   (6.9%)
Other challenger issues           =     1  (3.45%)

Challengers
----------------------------------
Not Relayed                       =     9 (31.03%)
Relayed                           =    10 (34.48%)
Unknown (Probably Not Relayed)    =    10 (34.48%)

```

What version of the tool are you using? Have you downloaded it recently?

@DCYeahThatsMe please provide your log files and let me know when you downloaded the tool.

**Comment by Secarius** [comment]
I configured my tool to download the newest version of your tool on startup.
So its the newest version :) (same for DCYeahThatsMe, he used also the newest version, as we both communicate before.

**Comment by DCYeahThatsMe** [comment]
@inigoflores yes, what @Secarius said is correct.  This has been happening for a few days at least now.  It happens on all the UG65 Milesight console.log files from various miners.
[console.log](https://github.com/inigoflores/helium-miner-log-analyzer/files/8453928/console.log)

I'll attach one as an example.

**Comment by Secarius** [comment]
But only on my windows machine. If i run it with ubuntu it works

**Comment by DCYeahThatsMe** [comment]
Yes, I am also running Windows.  I haven't installed any software specifically.... maybe there was a windows update, but nothing that I'm aware of.

**Comment by steakneedy** [comment]
Same here, running on Windows using Sensecap logs and the latest version of the script.

**Comment by inigoflores** [comment]
One of the latest commits introduced a bug on Windows. It should now be fixed. Please confirm.

**Comment by steakneedy** [comment]
> One of the latest commits introduced a bug on Windows. It should now be fixed. Please confirm.

Can confirm its working now on Windows 👍

**Comment by Secarius** [comment]
Yes it works now. Thank you very much for the fast support. 👍
