### ISSUE TITLE
only displaying last (few) witnesses ir normal?

### ISSUE THREAD

**Issue by s-areal** [inigoflores/helium-miner-log-analyzer#18]
Hello, 
I installed on sensecap and it worked.
But i can only display a few record, I mean, yesterday i could see about 120 but today only about 70.
Also i can't list yesterday's records.
Is this normal or am I using the wrong syntax?

![Captura de ecrã 2022-05-31, às 09 52 22](https://user-images.githubusercontent.com/49781569/171134444-b997d5ad-f6fd-4ff2-9e88-fa220c8c745a.png)

**Comment by inigoflores** [comment]
Hi

Unfortunately the logs are set to rotate when they reach 10 Mbytes, and only the last 5 are kept. Currently, with the high amount of logging that is taking place, this rotation happens every 3 or 4 hours, which means only the last 24 hours is currently being kept.

There are settings in sys.config which should be able modify the log rotation schedule. However, they seem not to work, just ignored by the miner.
