### ISSUE TITLE
Test Results from Controllino

### ISSUE THREAD

**Issue by DimitrisSar** [inigoflores/helium-miner-log-analyzer#2]
Hi,

Thanx for this script!

It works fine on a Controllino v1 miner

Log folder on Controllino v1: /var/log/miner/

**Comment by inigoflores** [comment]
Path added!

Thanks.

**Comment by DimitrisSar** [comment]
Forgot to mention: The Controllino v1 image (Raspbian = Debian GNU/Linux 11 (bullseye)) does not have a PHP parser by default installed so people would have to:
apt install php-cli
before running your script

Important note also: To gain access to the console of a Controllino v1, you need to open up the case and deploy your ssh key to the SD Card.  This action (opening the enclosure) will invalidate the warranty, so only expert users should try it at their own risk :(
