### ISSUE TITLE
how to open

### ISSUE THREAD

**Issue by lind-ucdcd** [inigoflores/helium-miner-log-analyzer#3]
hello... i can not open it i have this error maybe i went to wrong way can you tell me how to open it?
lind@Mehdis-iMac helium-miner-log-analyzer % ./processlogs.php
zsh: ./processlogs.php: bad interpreter: /usr/bin/php: no such file or directory

**Comment by inigoflores** [comment]
Hi

First step is to SSH into your miner. I believe you are trying to run the script from within your iMac. Not all miners have SSH open. Check with the manufacturer of your miner if this is possible. 

Once inside the miner, you need to install PHP. I've updated the Readme with a "Requirements" section and instructions on how to install PHP.

I hope it helps.
