### ISSUE TITLE
Witness per hour

### ISSUE THREAD

**Issue by microtransactions** [inigoflores/helium-miner-log-analyzer#5]
Awesome little script, would it be possible to add a feature to it? How many witnesses have been sent per hour. I usually get an idea of the state of the network by analyzing this and how many hotspots are sending beacons. Usually it's a constant number but sometimes it just goes way down.

**Comment by inigoflores** [comment]
Hi 

I'm glad you are finding the script useful :)

I've now added the requested metric:
````
$ ./processlogs.php 

Using logs in folder /opt/panther-x2/miner_data/log/


General Witnesses Overview  
----------------------------------
Total witnesses                   =   190  (3.46/hour)
Succesfully delivered             =   143 (75.26%)
Failed                            =    47 (24.74%) 
`````

As start & end times it uses those of the first and last witness being analyzed.

I hope it helps! Let me know if you have any comments.
